### ISSUE TITLE
add library to processing IDE

### ISSUE THREAD

**Issue by montoyamoraga** [dinchak/monome-processing#2]
hi!
is there a plan to add this library to the processing IDE?
has anyone tried to do it?
also, the monome fork of this library has no issues, can that be fixed?
or maybe transfer it to monome and open it to the everyone on the community and credit you @dinchak? any thoughts?
i am currently studying grids and i am trying out this library :)

**Comment by dinchak** [comment]
hello!!

as it stands i'm not really using or actively maintaining this library, so i'm happy to transfer it over to a new home.  monome sounds good or whatever is most appropriate! just let me know if i need to do anything to help support this effort.

thanks!

**Comment by montoyamoraga** [comment]
hi @dinchak !
i tihnk the right way to do it is deleting this repository, which then would ask you to name a new parent, and then you can say, the monome fork is the parent one now.
should we ask @tehn if this is ok?
i am happy to do it if you make me admin of the repo,
i would like to write more examples for this library, and it would be easier if it was part of monome :)

**Comment by dinchak** [comment]
that sounds great, thank you for the suggestion! i will do it now
